### ISSUE TITLE
Framework not found RSKImageCropper

### ISSUE THREAD

**Issue by KhangNg92** [ivpusic/react-native-image-crop-picker#1086]
hi all,

- Hope you guys have a good day. So I've been struggling with this error. 

`ld: framework not found RSKImageCropper`

- Here's my **Podfile**:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MakeModel' do
pod 'RSKImageCropper'
pod 'QBImagePickerController'
  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

And here's the result when I run `pod install` :

```
Analyzing dependencies
Fetching podspec for `RNImageCropPicker` from `../node_modules/react-native-image-crop-picker`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga/yoga.podspec`
Downloading dependencies
Using QBImagePickerController (3.4.0)
Using RNImageCropPicker (0.24.1)
Using RSKImageCropper (2.2.2)
Using React (0.59.9)
Using yoga (0.59.9.React)
Generating Pods project
Integrating client project
Sending stats
```

- I even select the **xworkspace**  to build the project but the error is still there. Please help

**Comment by pavermakov** [comment]
Same issue!

**Comment by bogdancochioras-clarisoft** [comment]
same issue!

**Comment by irajwani** [comment]
Hi, any updates here? I'm facing the same issue with RN 0.60.5 and my podfile is:

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'iosNottMyStyle' do
  # Pods for iosNottMyStyle
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  #pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

pod 'RSKImageCropper'
pod 'QBImagePickerController'
pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  target 'iosNottMyStyleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'iosNottMyStyle-tvOS' do
  # Pods for iosNottMyStyle-tvOS

  target 'iosNottMyStyle-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by irajwani** [comment]
Hi @ivpusic, your library is critical to my application. I hate that this error is preventing my app from building. Everything was fine with react native 0.55.3 and 0.59, but my project is now on 0.60.5.

**Comment by ivpusic** [comment]
you dont need explicitly specify these

pod 'RSKImageCropper'
pod 'QBImagePickerController'

try removing them from your Podfile. they will be pulled as part of this package podspec

**Comment by irajwani** [comment]
Thank you for the response @ivpusic 

I agree with what you are saying above; my Podfile did not previously contain

pod 'RSKImageCropper'
pod 'QBImagePickerController'
pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

so I removed them, deleted my Pods folder, re-installed my Pods folder, changed the .podspec for your library to say "React-Core" instead of "React/Core". Then I ran into the following issue: https://github.com/ivpusic/react-native-image-crop-picker/issues/1109

so I replaced <React/RCTImageLoader.h> with "RCTImageLoader.h" and then that issue went away, but then the build still fails because: 

<img width="891" alt="Screenshot 2019-10-06 at 4 34 26 AM" src="https://user-images.githubusercontent.com/25965881/66262066-c4b7ea00-e7f2-11e9-83d9-f6423cd7c36d.png">

I deleted folders within derived data and then tried to build again, but the build still failed because it could not find the framework RSKImageCropper.

This is how my project is structured, I tried moving RSKImageCropper explicitly to the Frameworks folder of both the .xcodeproj and the Frameworks folder under Pods, but it is throwing the same error each time.

<img width="263" alt="Screenshot 2019-10-06 at 4 42 08 AM" src="https://user-images.githubusercontent.com/25965881/66262117-bae2b680-e7f3-11e9-9ef6-38d3af5a0c03.png">

**Comment by irajwani** [comment]
UPDATE: Removing QBImagePicker.framework and RSKImageCropper.framework from "Link Binary with Libraries" seems to have resolved this. I think this makes sense because as of RN 0.60, the linking process is handled directly through Pods and we no longer need to add .xcodeproj files for each 3rd party dependency under the Libraries for our root .xcodeproj and similarly we don't need to add .a files for those 3rd party dependencies to "Link Binary with Libraries".

**Comment by ivpusic** [comment]
RSKImageCropper is not used anymore. please try latest version with TOCropViewController
