### ISSUE TITLE
react-native-picker:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by fanzhiri** [ivpusic/react-native-image-crop-picker#1096]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.? ["react-native-image-crop-picker": "^0.20.0"]
- react-native v0.?.? ["react-native": "0.55.3"]

### Platform
Tell us to which platform this issue is related
--- in Android

### Expected behaviour

build success

### Actual behaviour

> Task :react-native-picker:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-picker:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/slakofan/GitBlit/BuildKnow/node_modules/react-native-picker/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/slakofan/GitBlit/BuildKnow/node_modules/react-native-picker/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/slakofan/GitBlit/BuildKnow/node_modules/react-native-picker/android/build/intermediates/res/merged/release/values/values.xml:2718: error: resource android:attr/fontVariationSettings not found.
  /Users/slakofan/GitBlit/BuildKnow/node_modules/react-native-picker/android/build/intermediates/res/merged/release/values/values.xml:2719: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

### Steps to reproduce

1. $ cd android 

2. $./gradlew assembleRelease

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by fanzhiri** [comment]
close : go to the file name  node_module/react-native-image-crop-picker/android/build.gradle , change compileSdkVersion and targetSdkVersion to 28.

**Comment by ebhdeveloper** [comment]
It was linked to me twice
go to setting.gradle

**Comment by aniruddhbhamare** [comment]
above solution doesn't work for me...
compileSdkVersion and targetSdkVersion are already 28.

Version

react-native-image-crop-picker v0.?.?"react-native-image-crop-picker": "^0.28.0"
react-native v0.?.? "react-native": "0.61.5",

Platform
--- in Android

Expected behaviour
build success

Actual behaviour
Task :react-native-picker:verifyReleaseResources FAILED

What went wrong:
Execution failed for task ':react-native-picker:verifyReleaseResources'.
java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
/Users/slakofan/GitBlit/BuildKnow/node_modules/react-native-picker/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/slakofan/GitBlit/BuildKnow/node_modules/react-native-picker/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/slakofan/GitBlit/BuildKnow/node_modules/react-native-picker/android/build/intermediates/res/merged/release/values/values.xml:2718: error: resource android:attr/fontVariationSettings not found.
/Users/slakofan/GitBlit/BuildKnow/node_modules/react-native-picker/android/build/intermediates/res/merged/release/values/values.xml:2719: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Steps to reproduce
$ cd android

$./gradlew assembleRelease

> close : go to the file name node_module/react-native-image-crop-picker/android/build.gradle , change compileSdkVersion and targetSdkVersion to 28.

**Comment by sinclas** [comment]
This is still an issue.  I am getting the same error.   Was there any update on this?
