### ISSUE TITLE
IOS when I do not accept the camera rights, I cannot grant it permission again

### ISSUE THREAD

**Issue by namlee0005** [ivpusic/react-native-image-crop-picker#1182]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.26.1
- react-native v0.61.2

### Platform
Tell us to which platform this issue is related

- iOS

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by sa2812** [comment]
This is expected behaviour on iOS. On Android an app is able to keep requesting permission until the user accepts. On iOS after being denied permission, the only way to enable it is for the user to navigate to `Settings > [Your App Name] > Photos` and manually re-enable permissions there.

My suggestion would be to have a page or alert before asking for the system permission. If a user rejects there, then no problem, they can click on it again. If they accept the first prompt, they're likely to accept the system prompt. To add to this, if they still reject the system prompt, then go ahead and navigate them to a page explaining how to re-enable permissions.

It all takes a bit longer, but it does protect iOS users from being spammed for app permissions as developers can on Android.

**Comment by namlee0005** [comment]
After I denied the camera permission, I turned it on in settings. But iOS does not open the camera again
