### ISSUE TITLE
react-native-image-crop-picker didn't show any video files to pick from gallery.

### ISSUE THREAD

**Issue by Sajmal-P** [ivpusic/react-native-image-crop-picker#1981]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.38.1
- react-native v0.70.6

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Want to pick video from gallery using react-native-image-crop-picker

### Actual behaviour

react-native-image-crop-picker didn't show any video files to pick from gallery.

### Steps to reproduce

1. import ImagePicker from 'react-native-image-crop-picker'

2.ImagePicker.openPicker({
      mediaType: 'any',
    })
### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ReeturajThakur** [comment]
"In react-native-image-crop-picker, if you set the cropping option to true, the picker will only allow you to select photos, and videos will not be displayed for selection. This is because cropping is only applicable to images. If you want to select videos from the gallery, you need to either set cropping to false or omit it entirely. Additionally, ensure that the mediaType option is set to 'any' or 'video' to allow video selection."


        Example ---

        import ImagePicker from 'react-native-image-crop-picker';

        const pickerOptions = {
          width: 300,
          height: 300,
          multiple: true,        
          cropping: false,      
          mediaType: 'any',    
          showCropFrame: true,
          showCropGuidelines: false,
          freeStyleCropEnabled: true,
          cropperToolbarColor: '#FFFFFF',
          cropperStatusBarColor: '#000000',
         };

        ImagePicker.openPicker(pickerOptions)
        .then(images => {
          console.log(images);
         })
        .catch(error => {
          console.log('Error selecting media:', error);
         });
