### ISSUE TITLE
Unable to write to tmp location.

### ISSUE THREAD

**Issue by amrew** [ivpusic/react-native-image-crop-picker#239]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.4
- react-native v0.41.0

### Platform
Tell us to which platform this issue is related

- iOS

### Actual behaviour
I can't crop the image. After selecting the image, i can see the image preview. 
When i click `Choose`, the error appear.

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info
```
Warning: Attempt to present <UIAlertController: 0x7f9339486e70> on 
<QBImagePickerController: 0x7f93395526e0> whose view is not in the window hierarchy!
```

**Comment by ivpusic** [comment]
hmm, cannot reproduce this. can you give me more details? like code example

**Comment by amrew** [comment]
@ivpusic 
ups.. i get the real error now.
I think it's about ios permission, right?
Could you please help me.. 🙇 
```
{ [Error: Cannot save image. Unable to write to tmp location.]
  line: 7221,
  column: 20,
  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false',
  framesToPop: 1,
  code: 'E_CANNOT_SAVE_IMAGE',
  domain: 'RCTErrorDomain',
  userInfo: null,
  nativeStackIOS: 
   [ '0   salestockStaging                    0x0020f8fe RCTJSErrorFromCodeMessageAndNSError + 142',
     '1   salestockStaging                    0x00188542 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.224 + 178',
     '2   salestockStaging                    0x0015b1ae -[ImageCropPicker imageCropViewController:didCropImage:usingCropRect:] + 814',
     '3   salestockStaging                    0x0015b8e4 -[ImageCropPicker imageCropViewController:didCropImage:usingCropRect:rotationAngle:] + 180',
     '4   salestockStaging                    0x000c8d24 __39-[RSKImageCropViewController cropImage]_block_invoke_2 + 244',
     '5   libdispatch.dylib                   0x06c23396 _dispatch_call_block_and_release + 15',
     '6   libdispatch.dylib                   0x06c4ecc3 _dispatch_client_callout + 14',
     '7   libdispatch.dylib                   0x06c2e09a _dispatch_main_queue_callback_4CF + 1755',
     '8   CoreFoundation                      0x0480505e __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14',
     '9   CoreFoundation                      0x047c78df __CFRunLoopRun + 2319',
     '10  CoreFoundation                      0x047c6d5b CFRunLoopRunSpecific + 395',
     '11  CoreFoundation                      0x047c6bbb CFRunLoopRunInMode + 123',
     '12  GraphicsServices                    0x0733ab4c GSEventRunModal + 177',
     '13  GraphicsServices                    0x0733a9c7 GSEventRun + 80',
     '14  UIKit                               0x0103bff3 UIApplicationMain + 148',
     '15  salestockStaging                    0x000aed4c main + 140',
     '16  libdyld.dylib                       0x06c89799 start + 1' ] }
```

**Comment by ivpusic** [comment]
hm, do you have some time to debug this? here is the error line https://github.com/ivpusic/react-native-image-crop-picker/blob/bac8eebe884041607a2118ac312a5e10b76a9e60/ios/ImageCropPicker.m#L618

**Comment by clemmy** [comment]
I got this error too. It seems to not occur if I remove the `compressImageMaxWidth` option.

**Comment by mxmtsk** [comment]
Same happening for me. Providing `compressImageMaxHeight` is a workaround but I hope it get's a fix soon

**Comment by niocncn** [comment]
have same issue

**Comment by chrisbobbe** [comment]
This is still an issue and needs to be reopened. It seems to be caused by a bug in iCloud Photo Sharing. It seems to happen only when I select old photos whose originals are stored in iCloud, with compressed versions stored locally.

When requestImageDataForAsset is called, I'm seeing this log:

[Generic] Failed to load image data for asset <PHAsset: 0x13d041940> 87CCAFDC-A0E3-4AC9-AD1C-3F57B897A52E/L0/001 mediaType=1/0, sourceType=2, (113x124), creationDate=2015-06-29 04:56:34 +0000, location=0, hidden=0, favorite=0  with format 9999

So `[data writeToFile:filePath atomically:YES]` doesn't work, persistFile returns `nil`, and the E_CANNOT_SAVE_IMAGE error is thrown.

user2067021 does a good job of describing the problem at this Stack Overflow page, and I believe he or she is correct about the cause: https://stackoverflow.com/questions/28170444/photos-framework-requestimagedataforasset-occasionally-fails. Note that his or her answer was not marked as the accepted answer at the time I posted this; it can be found directly below the accepted answer.

One solution is to throw an error of some kind and gracefully fail, instead of just instantly closing the image picker. I'm not sure how specific that error should be, as users may be scared if they receive a call-to-action saying their iCloud photo cache is corrupted and they need to reset it.

**Comment by AlejandroCamps** [comment]
i have the same error when cropping if both move and scale are used. If i only scale the picture or only move it the save works well

**Comment by ju5td0m7m1nd** [comment]
Set atomically from YES to NO will solved the issue
ImageCropPicker.m L940
`BOOL status = [data writeToFile:filePath atomically:NO];`

**Comment by WillVill** [comment]
+ 1 for issue when cropping and scaling on iOS

**Comment by Volekss** [comment]
same here though

**Comment by hanzoow** [comment]
same issue here, @ivpusic
