### ISSUE TITLE
Work only first run app in IOS.

### ISSUE THREAD

**Issue by nickorsk2017** [ivpusic/react-native-image-crop-picker#243]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.9
- react-native v0.35.0

### Platform
Tell us to which platform this issue is related

- iOS

### Steps to reproduce

Work only first run app. After reinstall application work again only one run.

**Comment by ivpusic** [comment]
hmm, you are using a pretty outdated version of this library and react native. I suggest that you upgrade to one of the recent versions because many things changed since versions you are using. 

You can try example project, it includes recent versions of libraries, and if the issue is still there, please reopen the issue.
