### ISSUE TITLE
can not get the uri of picture on android

### ISSUE THREAD

**Issue by Style-Tender** [ivpusic/react-native-image-crop-picker#270]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.8
- react-native v0.42.0

### Platform
Tell us to which platform this issue is related
- Android

### Attachments
I'm sorry, this is not a issues. I just have a question can not be solved. Because I dded React Native to exist project, I don't know how to code `onActivityResult` method in my Activity ,and what lead to that I can not get the `uri` of picture in `js`.My Activity: `extends Activity implements DefaultHardwareBackBtnHandler`Anyone who can help me ? Thank you very much.

**Comment by ivpusic** [comment]
you can check provided example android project for how-to-do integration.

**Comment by stephenlaughton** [comment]
I am also running into this issue integrating react-native-crop-image-picker into a pre-existing native android codebase. The issue seems to be that I have defined ```onActivityResult``` in my android activity to handle some other necessary branching logic, and because of this PickerModule ```onActivityResult``` is being bypassed. Any suggestion how to call PickerModule ```onActivityResult``` manually from my existing Activity to relay the ```IMAGE_PICKER_REQUEST``` result?
