### ISSUE TITLE
how to fix the warning of "[ts] Module react-native-image-corp-picker has no default export"

### ISSUE THREAD

**Issue by freedomofme** [ivpusic/react-native-image-crop-picker#419]
### Version
- react-native-image-crop-picker v0.15.1
- react-native v0.47
- typescript v2.4.2
### Platform
- iOS
- Android

### Actual behaviour
 The following line will arise the warning I mentioned above by Ts.
    import ImagePicker from ‘react-native-image-corp-picker'

**Comment by chuece** [comment]
There is a typo in your import.
import ImagePicker from ‘react-native-image-**crop**-picker'

**Comment by ivpusic** [comment]
thanks @chuece

**Comment by freedomofme** [comment]
I am sorry for spelling mistakes , I post this issue on my phone .
The import is correct.
import ImagePicker from 'react-native-image-crop-picker'
I think this warning is caused by index.d.ts.
Could I open this issue again?

**Comment by joeldalley** [comment]
This appears to be a real problem, not merely a typo. The typo made was only in the original report, here, of the issue, not in @freedomofme's code. Or at least, that's plausible. Because I'm sure I'm importing it correctly, such that the library works in our application, and yet typescript compiler makes an error.

The error is simply that the `.d.ts` file doesn't match what actually occurs in the javascript `index.js` file. The JS file exports an object literal. The typescript declaration file asserts that individual functions are exported.

Anyone who takes seriously the output of the typescript compiler against javascript code + d.ts files in being burned by this error.

I believe this is one viable solution (in index.d.ts):
```
    export function openPicker(options: Options): Promise<Image | Image[]>;
    export function openCamera(options: Options): Promise<Image | Image[]>;
    export function openCropper(options: Options): Promise<Image>;
    export function clean(): Promise<void>;
    export function cleanSingle(path: string): Promise<void>;
    export default {
      openPicker,
      openCamera,
      openCropper,
      clean,
      cleanSingle
    }
```

**Comment by freedomofme** [comment]
sorry for the delayed response.

Adding the code posted by @joeldalley do worked.
export default {
      openPicker,
      openCamera,
      openCropper,
      clean,
      cleanSingle
    }

Now in typescript, we can coding in the way:

import ImagePicker, { Options } from 'react-native-image-corp-picker';

Should I post a PR?

**Comment by joeldalley** [comment]
@freedomofme yes, please do.

In our program, we take typescript compiler errors pretty seriously, and so right now we have to mute the error produced by this package. It would be nice to not have to do that. :-)

**Comment by ivpusic** [comment]
should be fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.17.0
