### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by damathryx** [ivpusic/react-native-image-crop-picker#48]
I get this error 
I've done the steps. not really sure what to do next

![screen shot 2016-08-23 at 4 25 09 pm](https://cloud.githubusercontent.com/assets/14576761/17885180/9cb34d18-694e-11e6-87d1-1e1c361afc7d.png)
![screen shot 2016-08-23 at 4 30 27 pm](https://cloud.githubusercontent.com/assets/14576761/17885243/f6e079dc-694e-11e6-8867-36415fb786a8.png)

![screen shot 2016-08-23 at 4 27 50 pm](https://cloud.githubusercontent.com/assets/14576761/17885177/9c49e184-694e-11e6-93f2-f0dce30593f8.png)
![screen shot 2016-08-23 at 4 27 20 pm](https://cloud.githubusercontent.com/assets/14576761/17885179/9cae3d5a-694e-11e6-8e6f-e02be82aa293.png)
![screen shot 2016-08-23 at 4 26 45 pm](https://cloud.githubusercontent.com/assets/14576761/17885178/9cab58a6-694e-11e6-8128-6a49362f8425.png)

**Comment by ivpusic** [comment]
you linked react-native-image-crop-picker already. It cannot work like this, because it is using external  dependencies, which are fetched by cocoa pods. Step by step is here https://github.com/ivpusic/react-native-image-crop-picker#ios-step-by-step-installation.

Probably now you have to run `rnpm unlink react-native-image-crop-picker`

**Comment by damathryx** [comment]
Thanks @ivpusic. but i get another error after doing unlink.
![screen shot 2016-08-25 at 10 21 19 am](https://cloud.githubusercontent.com/assets/14576761/17954456/c8e2836c-6aad-11e6-9dba-402ebe1c3433.png)

**Comment by damathryx** [comment]
@ivpusic I tried doing the steps again now I get Library not found for -IRNDocumentPicker
