### ISSUE TITLE
library not found for -lQBImagePickerController

### ISSUE THREAD

**Issue by summmmer** [ivpusic/react-native-image-crop-picker#546]
ld: warning: directory not found for option '-L/Users/infcn/Library/Developer/Xcode/DerivedData/fudao-bacfockisfovbogaixdqmfpqollg/Build/Intermediates/ArchiveIntermediates/fudao/BuildProductsPath/Release-iphoneos/QBImagePickerController'
 ld: warning: directory not found for option '-L/Users/infcn/Library/Developer/Xcode/DerivedData/fudao-bacfockisfovbogaixdqmfpqollg/Build/Intermediates/ArchiveIntermediates/fudao/BuildProductsPath/Release-iphoneos/RSKImageCropper'
 ld: library not found for -lQBImagePickerController
 clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ivpusic** [comment]
please read and execute all installation steps from README.

**Comment by songxiaoliang** [comment]
@summmmer Do you have a solution? I do not know how to solve it

**Comment by soroushchehresa** [comment]
this issue is happening when don't take completely step 2 of Post-install steps.
manual install not working and you can only use Cocoapods.
after install pod and take steps for resolve this error **open your-project.xcworkspace file with xcode and run project from here**.

NOTE:
your-project.xcworkspace file created after take step 2 of Post-install steps completely in ios folder of your project.
