### ISSUE TITLE
at a time when  released, a flashback occurred. But debug is ok.

### ISSUE THREAD

**Issue by shadowxxc** [ivpusic/react-native-image-crop-picker#547]

**Comment by ivpusic** [comment]
please provide more details and better description for an actual issue

**Comment by summmmer** [comment]
I have the same problem，At first，I have the following questions
ld: library not found for -lQBImagePickerController
clang: error: linker command failed with exit code 1 (use -v to see invocation)
and i switch in xcode from <my_app>.xcodeproj to <my_app>.xcworkspace, It's work

I have no problem testing，
But after packaging it into a IPA package, it flashes back.

**Comment by ivpusic** [comment]
it sounds like you didnt follow installation steps from readme. Please follow them and add required keys into info.plist as mentioned in readme file

**Comment by songxiaoliang** [comment]
@summmmer Do you have a solution? I do not know how to solve it

**Comment by summmmer** [comment]
@songxiaoliang 我用CocoaPods就一直找不到QBImagePickerController库，用xcode打开.xcworkspace工程就可以，你可以试试，如果不行就别用CocoasPos了。
手动的话就是测试就把 ios/ImageCropPickerSDK拉倒项目里，打包就是把Libraries/imageCropPicker.xcodeproj下面的两个拉倒常规选项下面的二进制下面

**Comment by soroushchehresa** [comment]
this issue is happening when don't take completely step 2 of Post-install steps.
manual install not working and you can only use Cocoapods.
after install pod and take steps for resolve this error **open your-project.xcworkspace file with xcode and run project from here**.

NOTE:
your-project.xcworkspace file created after take step 2 of Post-install steps completely in ios folder of your project.
