### ISSUE TITLE
Crashing on Android RN 0.59.2

### ISSUE THREAD

**Issue by thinklinux** [ivpusic/react-native-image-crop-picker#976]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.23.1
- react-native v0.59.2

### Platform
- Android

### Expected behaviour
Open a photo gallery

### Actual behaviour
Crashing with an error

### Steps to reproduce

```js
ImagePicker.openPicker()
```

### Attachments

![Screenshot 2019-03-29 at 9 05 43](https://user-images.githubusercontent.com/326949/55215257-dac06e80-5201-11e9-9420-7f1e6f49fd79.png)

I've reinstalled it couple of times. Tried other solutions in the issue tracker when the library is crashing but nothing is working. I don't have any issues on iOS.

Gradle version is the one that comes with RN 0.59.2
`classpath 'com.android.tools.build:gradle:3.3.1'`

It is the same on real device and in the emulator so I don't think that's the issue.

**Comment by elanpang** [comment]
also crash in iOS with Rn 0.59.2 ,  it seems caused by QBImage lib

**Comment by kwstasarva** [comment]
Also crashes on Android with RN 0.57.8.

**Comment by RichardLindhout** [comment]
I have this issue on iOS

**Comment by thinklinux** [comment]
It should be installation issue. Maybe because I'm using react-native-navigation and my MainApplication extends NavigationApplication like that: `public class MainApplication extends NavigationApplication`? Someone using react-native-navigation here and has more experience with it?

**Comment by dhavaljardosh** [comment]
facing the same issue. How can we add to android/ ios if we have the following file structure?
<img width="267" alt="Screen Shot 2019-04-23 at 3 29 23 AM" src="https://user-images.githubusercontent.com/18078687/56566356-0a9c3100-6578-11e9-9e4e-33fda202dd86.png">

**Comment by peacepostman** [comment]
Hello, 

We are using the same react-native version and the same react-native-image-crop-picker version without having any problem. Nevertheless I've been struggling to make it run without crash.

For ios what solved our problems was to include frameworks in the embedded binaries (see screen below)

<img width="790" alt="Capture d’écran 2019-04-24 à 09 12 36" src="https://user-images.githubusercontent.com/16117861/56639574-45ce5b00-6671-11e9-9bf6-8ac956b4de74.png">

For android the problem was caused by maven, the provided screen seemed to fix the implementation.

<img width="973" alt="Capture d’écran 2019-04-24 à 09 16 41" src="https://user-images.githubusercontent.com/16117861/56639811-d0af5580-6671-11e9-837f-33a97885505a.png">

Good luck !
